"""Flower ClientApp with SecAgg+ support."""

from pathlib import Path
from typing import List, Dict

import flwr as fl
import torch

from flwr.client.mod import secaggplus_mod

from fedmed.core.model import get_model
from fedmed.data.loader import create_brats_dataloader
from fedmed.data.partitioner import partition_iid

from fedmed.federation.client import FedMedClient


PROJECT_ROOT = Path(__file__).resolve().parents[2]

NUM_CLIENTS = 3
BATCH_SIZE = 2


def discover_brats_data(
    data_dir: Path,
) -> List[Dict[str, str]]:
    """Discover BraTS image/label pairs."""

    images_dir = data_dir / "imagesTr"
    labels_dir = data_dir / "labelsTr"

    if not images_dir.is_dir():
        raise FileNotFoundError(
            f"Images directory not found: {images_dir}"
        )

    if not labels_dir.is_dir():
        raise FileNotFoundError(
            f"Labels directory not found: {labels_dir}"
        )

    data_dicts = []

    for image_path in sorted(
        images_dir.glob("*.nii.gz")
    ):
        label_path = (
            labels_dir / image_path.name
        )

        if not label_path.is_file():
            continue

        data_dicts.append(
            {
                "image": str(image_path),
                "label": str(label_path),
            }
        )

    if not data_dicts:
        raise RuntimeError(
            f"No BraTS image/label pairs found in {data_dir}"
        )

    return data_dicts


def get_client_id(
    context: fl.common.Context,
) -> str:
    """Map Flower node identity to project client ID."""

    # Use the node ID to create a deterministic
    # three-client assignment.
    index = int(context.node_id) % NUM_CLIENTS

    return f"client_{index + 1}"


def client_fn(
    context: fl.common.Context,
) -> fl.client.Client:
    """Create one hospital Flower client."""

    client_id = get_client_id(context)

    # For the Day 2 integration test we use the
    # synthetic BraTS data generated by setup_data.py.
    data_dir = PROJECT_ROOT / "data" / "raw" / "brats"

    all_data = discover_brats_data(data_dir)

    partitions = partition_iid(
        all_data,
        num_clients=NUM_CLIENTS,
        seed=42,
    )

    client_data = partitions[client_id]

    if not client_data:
        raise RuntimeError(
            f"No training data assigned to {client_id}"
        )

    # Use the same partition for the local
    # training and validation loader in this
    # integration test.
    train_loader = create_brats_dataloader(
        client_data,
        batch_size=BATCH_SIZE,
        is_train=True,
        use_cache=False,
    )

    val_loader = create_brats_dataloader(
        client_data,
        batch_size=BATCH_SIZE,
        is_train=False,
        use_cache=False,
    )

    model = get_model(
        in_channels=4,
        out_channels=1,
    )

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    client = FedMedClient(
        client_id=client_id,
        model=model,
        train_loader=train_loader,
        val_loader=val_loader,
        device=device,
    )

    return client.to_client()


app = fl.client.ClientApp(
    client_fn=client_fn,
    mods=[
        secaggplus_mod,
    ],
)